t2scan: fix -std=c23 build failure
gcc-15 switched to -std=c23 by default:

    https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212

As a result `t2scan` fails the build so only typedef int bool
for __STDC_VERSION__ <= 201710L (C17)

    ../tools.h:35:15: error: two or more data types in declaration specifiers
       35 |   typedef int bool;
          |               ^~~~

Signed-off-by: Rudi Heitbaum <rudi@heitbaum.com>